from .core import (
    print,
    patch_color,
    unpatch_color,
    patch_log,
    unpatch_log,
    patch_prefix,
    unpatch_prefix,
    info,
    warn,
    error,
    exception,
    debug,
    set_show,
    is_show,
    show_debug,
    show_info,
    show_warn,
    show_error,
)
from .timing import timer, timer_start, timer_end

__all__ = [
    "print",
    "patch_color",
    "unpatch_color",
    "patch_log",
    "unpatch_log",
    "patch_prefix",
    "unpatch_prefix",
    "info",
    "warn",
    "error",
    "exception",
    "debug",
    "set_show",
    "is_show",
    "show_debug",
    "show_info",
    "show_warn",
    "show_error",
    "timer",
    "timer_start",
    "timer_end",
]

__version__ = "1.1.4"
